### ISSUE TITLE
DRAFT: As a node operator, I want a very portable sync client, so I don't have to use docker and docker compose

### ISSUE THREAD

**Issue by tamebadger** [GadzeFinance/etherfi-sync-client#6]
With Node.js v20 https://nodejs.org/api/single-executable-applications.html it's now possible to bundle node.js applications as a single executable, this would be great for the eth-sync-client to improve portability.

**Comment by solipsis** [comment]
I believe this is being picked up by @dbvora03  and @mingyuanlee
